agentSurvival.strideForward(1)
agentSurvival.scanBlocksAround(AgentSurvivalScanTarget.Water, 4, 2)
agentSurvival.scanFound()
agentSurvival.markScanResult(1)
agentSurvival.passiveMobsNearAgent(8)
agentSurvival.hostileMobsNearAgent(8)
agentSurvival.signal(AgentSurvivalSignal.Ready)
agentSurvival.sweepAttack(1)
agentSurvival.emeraldPowerAttack(1, 1, 2)
agentSurvival.markLastResult(1)
agentSurvival.chargeAttack(1, 1)
agentSurvival.lungeAttack(3, 1)
agentSurvival.strikeDirection(AgentSurvivalDirection.Back, 1)
agentSurvival.digDirection(AgentSurvivalDirection.Forward)
agentSurvival.drillLine(1)
agentSurvival.buildBridge(1, 1, 1)
agentSurvival.markInventoryCheck(1, 1, 1)
agentSurvival.reportLastCount()
