agentSurvival.strideForward(1)
agentSurvival.scanBlocksAround(AgentSurvivalScanTarget.Water, 4, 2)
agentSurvival.scanFound()
agentSurvival.passiveMobsNearAgent(8)
agentSurvival.hostileMobsNearAgent(8)
agentSurvival.sweepAttack(1)
agentSurvival.emeraldPowerAttack(1, 1, 2)
agentSurvival.chargeAttack(1, 1)
agentSurvival.lungeAttack(3, 1)
agentSurvival.digAxis(AgentSurvivalAxis.Forward, false)
agentSurvival.drillLine(1)
agentSurvival.buildBridge(1, 1, 1)
agentSurvival.reportLastCount()
